### ISSUE TITLE
CEP8: Wrong and non-changeable extension size

### ISSUE THREAD

**Issue by AAverin** [Adobe-CEP/CEP-Resources#158]
Platform: CEP8 Adobe CC 2018
Product: Adobe Photoshop 2018

If extension was already installed and is updated with the new version, window for the new extension version sets the wrong size and window can't be resized

**Comment by zimag** [comment]
Try to use the new
					<Geometry>
						<Size>
							<Width>400</Width>
							<Height>300</Height>
						</Size>
					    <MaxSize>
					        <Height>2160</Height>
					        <Width>3840</Width>
					    </MaxSize>
					    <MinSize>
					        <Height>10</Height>
					        <Width>256</Width>
					    </MinSize>
					</Geometry>

structure and use dimensions multiplied by 2.

At first I had the same issue but now all the windows are resizeable.

**Comment by AAverin** [comment]
I have this geometry at the moment:
```
<Geometry>
                        <Size>
                            <Height>380</Height>
                            <Width>300</Width>
                        </Size>
                        <MaxSize>
                            <Height>380</Height>
                            <Width>400</Width>
                        </MaxSize>
                        <MinSize>
                            <Height>380</Height>
                            <Width>250</Width>
                        </MinSize>
                    </Geometry>
```

how do you propose to change it?

**Comment by zimag** [comment]
Try to double the maximum dimensions. Them must be some sort of retina or dpi dependent values.

**Comment by AAverin** [comment]
I see, thanks.
Would be also great to have some kind of official response from CEP developers on this matter.
So far it looks like a bug to me, or I am missing some requirements for size dimensions that would make it work

**Comment by undavide** [comment]
As far as I know, it is an acknowledged bug. It should have been logged – we waited for a fix in the first PS update, but it didn't arrive (or it didn't work as expected).

**Comment by AAverin** [comment]
I will try playing with size values.
Any other known workarounds already?
Maybe a script to disable and re-enable extension via Window -> Extensions?

**Comment by VishakhaVaidya** [comment]
There are a few bugs related to resizing, that we are fixing. 
@AAverin  for the values you are using, the extension should be resizable until the min and max values, unless its a part of panel group which overrides the min and max limits. If you undock it and are still not able to resize, its definitely a bug.  
@zimag extension developers should not be bothered about monitor dpi, thats taken care of by application and CEP, if the application is dpi aware.

**Comment by AAverin** [comment]
@VishakhaVaidya I have a screenshot from an alpha-tester with panel undocked and wrong size. Can't really see if panel is non-resizeable, but that was other testers complained about.
I myself saw this behaviour with panel docked – panel group was not resizeable with my panel inside

**Comment by VishakhaVaidya** [comment]
@AAverin This looks like a bug we are already fixing. I will check it after the fix. Can you help me with some more info, 

1. is this happening with a monitor scale factor greater than 1
2. Is this a platform specific behavior, happening only on win or mac?

Thanks.

**Comment by zimag** [comment]
I have to double the dimensions with PS GUI scale factor of 1 on Win10.

**Comment by AAverin** [comment]
@VishakhaVaidya 
I have played around a bit more and looks like the issue is:
- if panel is already attached to a group and you change manifest, restart Photoshop, size may look correct. But, once you detach the panel of the group – size starts to draw somehow wrong, shorter. If you then put panel back to the group size is still wrong.

So what I did in the end – fixed my size and made it larger. Now panel is not cut when detached anymore, but it might show up larger then needed when attached to a group.

So as I see, there seems to be a size bug related to groups of panels.

**Comment by VishakhaVaidya** [comment]
@AAverin thanks for the info, I will take a look.

**Comment by rasesh1995** [comment]
@AAverin I am unable to reproduce the issue. Can you attach a video of what causes the issue to happen to enable me to fix it

**Comment by undavide** [comment]
FYI, it happens to me on Sierra + HighSierra, will try to record a video asap.

**Comment by zimag** [comment]
Completely forgot that I can't reisize my panels either, except if they are docked together with a native Timeline panel. If this panel is present in the column of panels the resizing magically working. All I have to to is to put a collapsed Timeline or other panel between them.

**Comment by zimag** [comment]
Was there an update today in the background? 
Just asking because now I can freely resize the undocked panels.
But I am experiencing heavy lag in my log panel. Something else must have been changed too.

**Comment by AAverin** [comment]
Just in case David didn't send you anything yet, here is a video of the bug (Video is unlisted on Youtube)
https://youtu.be/BhJp1r38SvM

By default, panel opens in a tab group, where size is calculated wrong.
Detaching a panel into icon fixes size problem, and size is calculated correctly even if after you re-attach it to the same group

**Comment by bialikover** [comment]
Any updates on this issue?

**Comment by ErinFinnegan** [comment]
@bialikover There were several bug reports internally, like CEP-826 and CEP-940.

I'm still asking around, but the bug seems to have been fixed for [CEP 9, which is currently in prereleases](https://medium.com/adobetech/cep-9-0-is-available-now-in-the-creative-cloud-developer-prereleases-bb50e9070828).

**Comment by ErinFinnegan** [comment]
Hi @bialikover! I have confirmed that this bug is fixed in the upcoming release of CEP 9, and there are currently no plans to fix it in CEP 8. I suspect this might then affect some products if they happen to have a maximum of CEP 8 support. When CEP 9 comes out there will likely be [a version chart similar to the one in the CEP Cookbook](https://github.com/Adobe-CEP/CEP-Resources/blob/master/CEP_8.x/Documentation/CEP%208.0%20HTML%20Extension%20Cookbook.md#applications-integrated-with-cep).

I could be wrong, though...

**Comment by AAverin** [comment]
@ErinFinnegan thanks for clarification.
Do you have some mailing list I can subscribe to be informed about pre-releases so I could update my product for new version beforehand?

**Comment by ErinFinnegan** [comment]
@AAverin got in touch with me, and I added him to the new Adobe Creative Cloud Developer Newsletter (online signup form coming soon).

Pre-release information for different products [are listed in this blog post](https://medium.com/adobetech/cep-9-0-is-available-now-in-the-creative-cloud-developer-prereleases-bb50e9070828), and if you follow [the Adobe Tech blog](https://medium.com/adobetech), we'll announce it there when CEP 9 goes public.

**Comment by ErinFinnegan** [comment]
This is fixed in CEP 9, so this issue can be closed.  (@prernavij ?)

Here's the newsletter sign up link: https://adobe.ly/devnews

**Comment by prernavij** [comment]
Closing as it's fixed as Erin mentioned above.

**Comment by pixels4nickels** [comment]
IF this is fixed in CEP 9, how are we supposed to target that version? There seems to be a bug still in CC2019 that prevents your panel from appearing if you set the 
<ExtensionManifest Version="10.0"
<RequiredRuntime Name="CSXS" Version="10.0" 

Our LSR viewer panel has been non-resizable for 2 releases now because of this regression and our users continue to wait for a fix.

**Comment by pixels4nickels** [comment]
I am able to target CEP 9 using version="9.0" but the panel is still not resizable.
