### ISSUE TITLE
[CEP-2215]CEP Extensions crashes on new Illustrator/Photoshop 2021 releases

### ISSUE THREAD

**Issue by zhangusc** [Adobe-CEP/CEP-Resources#320]
Found two issues on Illustrator 25 and Photoshop 22 (CEP 10) on macOS with a secondary monitor connected. I have attached a simple CEP extension for Adobe to investigate the issues. Download the zip file [com.esri.cep10crash.zip](https://github.com/Adobe-CEP/CEP-Resources/files/5432084/com.esri.cep10crash.zip). Unzip the file and place the folder under your CEP extensions folder on macOS.

Reproducible steps are included in the extension itself (See image below). Both are critical issues affecting all CEP extensions including Adobe’s own “Library” extension across multiple Adobe 2021 apps (e.g. Illustrator, Photoshop, etc.). I hope Adobe can move quickly and have a fix for those issues.

![crash](https://user-images.githubusercontent.com/7468979/97061128-936ba280-154a-11eb-9a43-56fe47b2939a.png)

**Comment by sujaisivanandan** [comment]
@zhangusc  Thanks for testing and reporting this issue.

With the provided extension and steps, I am able to reproduce a problem where the layout of the extension goes into a weird state and also the video no longer plays. I dont get any crash reported in console though. I'm investigating the layout problem when moving between monitors. However wanted to confirm if this is the same what you are seeing or do you see a specific crash in your console?

**Comment by zhangusc** [comment]
@sujaisivanandan When I say crash, I mean the extension is totally frozen and no longer responsive. The only way to fix the issue is to restart Illustrator. This issue is related to the complexity of the HTML panel. It is less likely to be reproduced in a simple HTML page with text only, and more frequently reproduced in a complicated HTML, having frames, images, tables, etc. With a video player on the page, I can reproduce it almost every time I move the panel from one monitor to the other.  It is a showstopper for us to release our extension to support Adobe CC 2021 apps. Please have the issues fixed or at least provide an acceptable workaround.

**Comment by sujaisivanandan** [comment]
Thanks for the details @zhangusc.
Yes I'm looking into this, however in the meantime please do refer to https://github.com/Adobe-CEP/CEP-Resources/blob/master/CEP_10.x/Documentation/Issues.md#faq and ensure that you have updated node modules to what is supported with node version 12.3.

**Comment by zhangusc** [comment]
@sujaisivanandan In the attached sample extension, nodejs is not enabled

**Comment by tomzag** [comment]
Here 2 screenshots from 2 of my customers:

[https://snipboard.io/1tLUQV.jpg](https://snipboard.io/1tLUQV.jpg)
[https://snipboard.io/Io6adj.jpg](https://snipboard.io/Io6adj.jpg)

The first one is from InDesign, so I think this is not host app related.
Both CEP panels don't have enabled nodejs.

**Comment by sujaisivanandan** [comment]
@tomzag Is thsi again happening in a dual monitor setup - the screenshot you have attached?

**Comment by tomzag** [comment]
Yes.

**Comment by sujaisivanandan** [comment]
Tracked internally with ID: CEP-2215 - cc: @ErinFinnegan

**Comment by zhangusc** [comment]
@sujaisivanandan @ErinFinnegan Any update on this issue?

**Comment by ErinFinnegan** [comment]
Hi @zhangusc !

Sujai says they're getting closer to a fix.

**Comment by ErinFinnegan** [comment]
Hi @zhangusc !

There's work scheduled for this in a January sprint. Just keeping you updated!

**Comment by zhangusc** [comment]
@ErinFinnegan Any update on this issue?

**Comment by ErinFinnegan** [comment]
The JIRA ticket is still getting updated, there was a test three days ago. They're testing it on M1 processors, too.

@sujaisivanandan might have more insight... This is CEP-2251, right?

**Comment by ErinFinnegan** [comment]
🤔 Well, now this is scheduled for an April sprint.

The good news is that this error does not seem to happen on M1.

**Comment by ErinFinnegan** [comment]
This is now marked as fixed in CEP 11.1.0.49 and above, and the JIRA ticket is closed.

**Comment by zhangusc** [comment]
@ErinFinnegan Is there an Illustrator/Photoshop prerelease with CEP 11.1.0.49 that we can use to verify the fix?

**Comment by ErinFinnegan** [comment]
Not yet! But there will be this summer.

**Comment by zhangusc** [comment]
@ErinFinnegan Check the attached extension on illustrator 25.4.1. Problem 1 is fixed, but problem 2 is still occurring.

**Comment by sujaisivanandan** [comment]
@zhangusc are the repro steps for problem-2 the same as what s mentioned in the first thread? I'm not able to repro this. Please confirm.

**Comment by zhangusc** [comment]
@sujaisivanandan Double checked it again. Correct the version number above. Problem 2 is still reproducible on Illustrator 25.3.1 (macOS). It is not reproducible on Illustrator 35.4.1 (macOS). As Illustrator 25.3.1 shipped with CEP 11.1.0.81 and the issue was fixed in CEP 11.1.0.49, should I expect a fix in Illustrator 25.3.1? Reproducible steps are the same as listed below
![image](https://user-images.githubusercontent.com/7468979/131297303-a79a21a8-cb2d-48b1-ba7e-71358088d66c.png)

**Comment by sujaisivanandan** [comment]
@zhangusc the issue was fixed in CEP 11.2.0.100 which is part of Illustrator 25.4.1 and InDesign 16.4.
From your above description, I understand that you are not seeing the issue with these builds. 
Note: this Fix will not be patched on earlier 25.x versions and should be available on Illustrator 25.4.1 and higher versions only.
